apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageupdaterdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageupdaterdemo
  template:
    metadata:
      labels:
        app: imageupdaterdemo
    spec:
      containers:
      - name: imageupdaterdemo
        image: sanjithmohanan/ghaction:2.3.4
        ports:
        - containerPort: 80