apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sinplek8s
  namespace: argocd
  finalizers:
    #delete the resources created by this application. Without this, the k8s resource remains
    - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: 'https://github.com/SanjithMohanan/simpleK8s'
    targetRevision: HEAD
    path: argocdbasic
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true 
      - PruneLast=true